[package]
name = "cargo-listdeps"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-license = "0.4.2"
cargo_metadata = "0.14.1"
cargo_toml = "0.10.3"
structopt = "0.3.25"
